In [65]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

In [66]:
json_dir = Path("../../data/raw")

dir_names = []
for json_file in json_dir.glob("*.json"):
    if json_file.name not in {'scraped_videos_tracker.json'}:
        dir_names.append(json_file.name)
dir_names

['AsmonTV_batch_20260608_205250.json',
 'CoryxKenshin_batch_20260608_205250.json',
 'dream_batch_20260608_205250.json',
 'FlameFragsMC_batch_20260608_205250.json',
 'IShowSpeed_batch_20260608_205250.json',
 'ItsUzoth_batch_20260608_205250.json',
 'markiplier_batch_20260608_205250.json',
 'MrBeastGaming_batch_20260608_205250.json',
 'ParrotX2_batch_20260608_205250.json',
 'penguinz0_batch_20260608_205250.json',
 'Spokeishere_batch_20260608_205250.json',
 'xQcOW_batch_20260608_205250.json']

In [67]:
dfs = []
for dir_name in dir_names:
    df = pd.read_json(json_dir / dir_name)
    df['channel_name'] = dir_name.split('_')[0]
    dfs.append(df)
display(dfs[0].head())
display(dfs[1].head())

,video_id,text,likes,published_at,channel_name
0,hOZd3wF0i7I,"""They targeted me because of my race!""\n\n*Bla...",746,2026-06-08 19:06:39+00:00,AsmonTV
1,hOZd3wF0i7I,this lady was a dlc character for concord 🤣,776,2026-06-08 19:14:09+00:00,AsmonTV
2,hOZd3wF0i7I,"""They axed me""\n\nThe fatigue man",246,2026-06-08 20:27:18+00:00,AsmonTV
3,hOZd3wF0i7I,Noticing Patterns fatigue,1802,2026-06-08 18:01:40+00:00,AsmonTV
4,hOZd3wF0i7I,"""When you get used to preferential treatment, ...",1209,2026-06-08 18:17:17+00:00,AsmonTV

,video_id,text,likes,published_at,channel_name
0,E91hRBbJObI,its like a toxic relationship,7377,2026-05-13 13:35:43+00:00,CoryxKenshin
1,E91hRBbJObI,and all of a sudden my sundays weren’t scary a...,2583,2026-05-24 02:11:24+00:00,CoryxKenshin
2,E91hRBbJObI,Spooky scary someday,714,2026-06-06 09:51:34+00:00,CoryxKenshin
3,E91hRBbJObI,"It’s okay guys, only 7 months more!",306,2026-05-31 23:36:40+00:00,CoryxKenshin
4,E91hRBbJObI,"We've had a war, new viral outbreak, ufo files...",1883,2026-05-21 10:09:32+00:00,CoryxKenshin

In [68]:
df = pd.concat(dfs)
display(df.sample(10))
display(df.info())

,video_id,text,likes,published_at,channel_name
26990,qaKbCsV53sg,10:55 why he looking at us like we pushing him...,74,2024-04-02 19:10:07+00:00,markiplier
33410,3khTYP_vTqw,"1:02 ""It was good. Like very good actually."" t...",5338,2025-12-25 17:52:38+00:00,penguinz0
32323,XQ_Cp5VI_MU,My anxiety while watching this📈😨,3015,2025-03-30 06:36:37+00:00,IShowSpeed
36602,hpCAnwC3HT0,*S-S-S-SAMURAI SLICE THAT LIKE BUTTON IF YOU’R...,863,2019-04-07 04:07:32+00:00,CoryxKenshin
14460,jDVr_ICpX-E,21:27 the human torch,13,2022-03-16 13:57:54+00:00,CoryxKenshin
36164,8MshTCBV94w,Nobody:\n\n\n*Cory’s character starts walking*...,138,2019-04-12 02:28:47+00:00,CoryxKenshin
36931,YzICf5HFSYY,Love that the breach starts in the exact same ...,99,2023-06-23 13:05:41+00:00,markiplier
45395,l0xP8tBjZYs,"i love how mark says ""wai wai wait a minute"" i...",3,2023-01-11 22:01:22+00:00,markiplier
22177,uOl1oIhvJlo,"Aliens: ""...The Dow is under $50,000 now, right?""",455,2026-02-21 07:57:22+00:00,penguinz0
22318,KjRfXURKAx8,Dream: tnt launcher \nGeorge: aight *pulls out...,3042,2020-06-11 09:55:21+00:00,dream

<class 'pandas.DataFrame'>
Index: 400620 entries, 0 to 43680
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   video_id      400620 non-null  str
 1   text          400620 non-null  str
 2   likes         400620 non-null  int64
 3   published_at  400620 non-null  datetime64[us, UTC]
 4   channel_name  400620 non-null  str
dtypes: datetime64[us, UTC](1), int64(1), str(3)
memory usage: 18.3 MB

None

In [69]:
import re

def tokenize(text):
    text = text.lower()
    return re.findall(r"\b[a-z0-9]+\b", text)

df['tokens'] = df['text'].apply(tokenize)
df.sample(5)

,video_id,text,likes,published_at,channel_name,tokens
23164,Xke-af3vIoE,58:45 “ MY NAME IS EMMA!!!” killed me 😭😭😭,255,2022-09-19 03:50:40+00:00,CoryxKenshin,"[58, 45, my, name, is, emma, killed, me]"
20602,Hr2U0OLOMDA,discord’s ceo is Israeli btw,6,2026-02-10 15:32:37+00:00,xQcOW,"[discord, s, ceo, is, israeli, btw]"
6657,zBa6cYbnWPY,"26:36\n""Swansea, don't hit Daisuke with the ax...",429,2025-01-02 01:48:27+00:00,CoryxKenshin,"[26, 36, swansea, don, t, hit, daisuke, with, ..."
12184,e7PoZVXV2vA,Would be so much easier to believe if it wasn’...,0,2026-05-23 00:05:15+00:00,AsmonTV,"[would, be, so, much, easier, to, believe, if,..."
39894,WHgJX12AhTQ,Bro thought Vini about to win,67,2024-10-28 22:20:01+00:00,IShowSpeed,"[bro, thought, vini, about, to, win]"

In [70]:
original_df = df.copy()
df = df.explode('tokens')
df = df.rename(columns={"tokens": "word"})

In [71]:
display(df.sample(5))
display(original_df.sample(5))

,video_id,text,likes,published_at,channel_name,word
32319,_vEQmbru_n8,Charlie complaining about the grenade launcher...,0,2026-03-07 19:45:59+00:00,penguinz0,you
33380,BxvneqcXsqo,This proves X is full of dogshit and ragebait....,1,2025-12-14 10:55:45+00:00,xQcOW,x
9224,QNAgawC5hbM,The black knight satellite is actually just a ...,1,2026-04-25 18:40:24+00:00,penguinz0,then
33070,003LNFd-MXE,Mythical refresh,101,2025-12-13 20:22:01+00:00,xQcOW,mythical
15321,lxOiRbbD1ZQ,"""...thas such an ego play..."" greek please stf...",3,2026-03-16 18:51:07+00:00,xQcOW,you

,video_id,text,likes,published_at,channel_name,tokens
6632,3yam-9Vw700,I LOVE THIS SMP EVERY TIME THIS SMP IS UPLOADE...,7,2022-02-05 00:39:31+00:00,Spokeishere,"[i, love, this, smp, every, time, this, smp, i..."
10709,mBO3sIveq3I,What up vod viewers 🧙‍♂️,274,2025-08-21 13:08:47+00:00,dream,"[what, up, vod, viewers]"
10032,2TIy6k4mHec,Leaving the body of someone you murdered in th...,2775,2026-04-18 17:41:33+00:00,penguinz0,"[leaving, the, body, of, someone, you, murdere..."
1682,4He0k2FSx7Q,28:22 PARROT I SWEAR TO GOD,6,2026-02-01 20:21:52+00:00,ParrotX2,"[28, 22, parrot, i, swear, to, god]"
47027,cY8wiaYI-wo,"It's black ops 4 game, pubg map, and a fortnit...",76,2018-09-10 23:02:27+00:00,CoryxKenshin,"[it, s, black, ops, 4, game, pubg, map, and, a..."

In [72]:
latest = df["published_at"].max()

df["week"] = ((latest - df["published_at"]).dt.days // 7)
df = df[df["week"] < 20]

In [73]:
df.sample(5)

,video_id,text,likes,published_at,channel_name,word,week
22359,ssYXDYuuxdc,"Rumor has it, Guinness World Records got the n...",8,2026-02-20 19:11:37+00:00,penguinz0,guinness,15
5222,ziT5UIY_5y4,You cannot take one of the machines then be on...,8,2026-05-09 17:16:35+00:00,xQcOW,from,4
9452,PC5RAJbjq-c,The first video with the guy with glowing blue...,1687,2026-04-21 17:42:25+00:00,penguinz0,campaign,6
20828,g-OzsyLn6jw,The worst part is they think that just because...,449,2026-04-16 07:13:56+00:00,AsmonTV,think,7
5154,05CNs0GpFEM,Quite a day!,1,2026-05-11 23:52:41+00:00,penguinz0,day,4

In [74]:
agg = df.groupby(["word", "week"]).agg(
    count=("word", "size"),
    likes=("likes", "sum")
).reset_index()

In [75]:
agg.sample(5)

              word  week  count  likes
65049         down     1    119  84104
200715  suspension     2      2      2
7145     according     8      1   2928
33524        cages     6      1     21
64058       dollar     6      9   2727

In [76]:
count_pivot = agg.pivot(index="word", columns="week", values="count").fillna(0).astype(int)
count_pivot.columns = [f"week_{c}_count" for c in count_pivot.columns]

In [77]:
count_pivot.sample(5)

,week_0_count,week_1_count,week_2_count,week_3_count,week_4_count,week_5_count,week_6_count,week_7_count,week_8_count,week_9_count,week_10_count,week_11_count,week_12_count,week_13_count,week_14_count,week_15_count,week_16_count,week_17_count,week_18_count,week_19_count
word,,,,,,,,,,,,,,,,,,,,
neighborly,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
gloves,2,3,1,2,2,1,0,0,0,0,3,0,2,5,1,0,0,2,1,0
worths,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
climb,1,0,1,1,6,13,3,2,2,0,8,6,7,4,1,2,1,1,1,0
contacting,1,1,2,2,0,1,0,0,0,0,0,0,1,0,0,1,1,1,0,0

In [78]:
likes_pivot = agg.pivot(index="word", columns="week", values="likes").fillna(0).astype(int)
likes_pivot.columns = [f"week_{c}_likes" for c in likes_pivot.columns]

In [79]:
likes_pivot.sample(5)

,week_0_likes,week_1_likes,week_2_likes,week_3_likes,week_4_likes,week_5_likes,week_6_likes,week_7_likes,week_8_likes,week_9_likes,week_10_likes,week_11_likes,week_12_likes,week_13_likes,week_14_likes,week_15_likes,week_16_likes,week_17_likes,week_18_likes,week_19_likes
word,,,,,,,,,,,,,,,,,,,,
stimulated,0,0,0,0,0,0,0,0,506,3,0,0,0,0,0,0,0,0,0,0
dise,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
diff,0,0,28,0,0,37,0,76,0,92,0,0,0,0,0,0,0,0,0,107
desire,1124,1,0,464,177,425,140,140,0,12,10,0,6,7,595,0,0,8884,300,52
hermit,8743,0,0,2,0,2521,0,0,0,63,0,13,0,0,0,1315,11,0,894,0

In [80]:
final_df = pd.concat([count_pivot, likes_pivot], axis=1).fillna(0)

In [81]:
final_df.sample(5)

,week_0_count,week_1_count,week_2_count,week_3_count,week_4_count,week_5_count,week_6_count,week_7_count,week_8_count,week_9_count,...,week_10_likes,week_11_likes,week_12_likes,week_13_likes,week_14_likes,week_15_likes,week_16_likes,week_17_likes,week_18_likes,week_19_likes
word,,,,,,,,,,,,,,,,,,,,,
reckoning,0,0,0,0,1,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
counteract,1,0,0,0,0,0,1,0,0,0,...,0,0,66,0,0,0,0,0,0,0
hime,0,0,0,0,0,0,0,0,0,0,...,0,0,0,111,0,0,0,0,0,3
evolving,0,0,1,1,1,1,1,0,2,2,...,0,6,0,150,0,491,0,6264,0,0
firefighters,0,0,1,0,0,1,2,0,0,0,...,0,0,0,0,0,20,0,0,16,0

In [64]:
final_df.info()

<class 'pandas.DataFrame'>
Index: 53848 entries, 0 to zzzzzzzzzzzzzzzzzzzz
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   week_0_count   53848 non-null  float64
 1   week_1_count   53848 non-null  float64
 2   week_2_count   53848 non-null  float64
 3   week_3_count   53848 non-null  float64
 4   week_4_count   53848 non-null  float64
 5   week_5_count   53848 non-null  float64
 6   week_6_count   53848 non-null  float64
 7   week_7_count   53848 non-null  float64
 8   week_8_count   53848 non-null  float64
 9   week_9_count   53848 non-null  float64
 10  week_10_count  53848 non-null  float64
 11  week_11_count  53848 non-null  float64
 12  week_12_count  53848 non-null  float64
 13  week_13_count  53848 non-null  float64
 14  week_14_count  53848 non-null  float64
 15  week_15_count  53848 non-null  float64
 16  week_16_count  53848 non-null  float64
 17  week_17_count  53848 non-null  float64
 18  week_18_count  53848 non-null  float64
 19  week_19_count  53848 non-null  float64
 20  week_0_likes   53848 non-null  float64
 21  week_1_likes   53848 non-null  float64
 22  week_2_likes   53848 non-null  float64
 23  week_3_likes   53848 non-null  float64
 24  week_4_likes   53848 non-null  float64
 25  week_5_likes   53848 non-null  float64
 26  week_6_likes   53848 non-null  float64
 27  week_7_likes   53848 non-null  float64
 28  week_8_likes   53848 non-null  float64
 29  week_9_likes   53848 non-null  float64
 30  week_10_likes  53848 non-null  float64
 31  week_11_likes  53848 non-null  float64
 32  week_12_likes  53848 non-null  float64
 33  week_13_likes  53848 non-null  float64
 34  week_14_likes  53848 non-null  float64
 35  week_15_likes  53848 non-null  float64
 36  week_16_likes  53848 non-null  float64
 37  week_17_likes  53848 non-null  float64
 38  week_18_likes  53848 non-null  float64
 39  week_19_likes  53848 non-null  float64
dtypes: float64(40)
memory usage: 16.8+ MB